Project_P1/MvcLayer/Controllers/ItemController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ModelsLibrary;
using ModelsLibrary.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace MvcLayer.Controllers
{
    public class ItemController : Controller
    {
        private readonly ILogger<ItemController> _logger;

        private readonly IItemLogic _itemLogic;
        //private readonly IItemLogic _cart;
        //create a constructor into which i'll inject the business layer.
        public ItemController(IItemLogic itemLogic)
        {
            this._itemLogic = itemLogic;
            //this._logger = logger;
        }
        // GET: ItemController
        public ActionResult Index()
        {
            return View();
            
        }
        // From Locations View, To Items View
        // Initializes Cart
        public ActionResult CreateCart(IDictionary<String, String> parms)
        {
            parms.TryGetValue("CustomerId", out string customerIdStr);
            parms.TryGetValue("StoreId", out string storeIdStr);
            int customerId = Int32.Parse(customerIdStr);
            int storeId = Int32.Parse(storeIdStr);
            var cart = new CartViewModel()
            {
                CustomerId = customerId,
                StoreId = storeId,
                Items = new List<ItemViewModel>(),
            };
            HttpContext.Session.SetString("CartSession", JsonConvert.SerializeObject(cart));
            return RedirectToAction("Items", new { id = storeId });
        }
        // From CreateCart or Cart, To AddtoCart
        public async Task<ActionResult> Items(int id)
        {
            List<ItemViewModel> items = await _itemLogic.QueryItemView(id);
            return View(items);
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Items(ItemViewModel model)//model binding system takes the dat from the form and matches it to the props of the model.
        {
            
            //check that the model binding worked.
            if (!ModelState.IsValid)
            {
                RedirectToAction("Items");
            }
            
            return View("AddToCart", model);
        }
        public ActionResult AddToCart(IDictionary<String, String> parms)
        {
            parms.TryGetValue("ProductId", out string id);
            parms.TryGetValue("Stock", out string stock);
            return View(_itemLogic.GetItemViewModelFromProductId(Int32.Parse(id),Int32.Parse(stock)));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToCart(ItemViewModel model)//model binding system takes the dat from the form and matches it to the props of the model.
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            else if(model.OrderQuantity>model.Stock)
            {
                //ViewBag.ErrorText = "Hey guy, there was an error!";
                ModelState.AddModelError(nameof(ItemViewModel.OrderQuantity), "This store does not have that amount of items");
                return View(model);
            }
            CartViewModel cart = JsonConvert.DeserializeObject<CartViewModel>(HttpContext.Session.GetString("CartSession"));
            cart = _itemLogic.AddItemToCart(cart, model);
            HttpContext.Session.SetString("CartSession", JsonConvert.SerializeObject(cart));
            return RedirectToAction("Cart");
        }
        public ActionResult Cart()
        {
            CartViewModel cart = JsonConvert.DeserializeObject<CartViewModel>(HttpContext.Session.GetString("CartSession"));
            ViewData["storeId"] = cart.StoreId;
            ViewData["customerId"] = cart.CustomerId;
            return View(cart.Items);
        }
        public ActionResult VerifyCart()
        {
            CartViewModel cart = JsonConvert.DeserializeObject<CartViewModel>(HttpContext.Session.GetString("CartSession"));
            return View(cart.Items);
        }
        public async Task<ActionResult> CreateNewOrder()
        {
            //if (!ModelState.IsValid)
            //{
            //    RedirectToAction("SignUp");
            //}
            CartViewModel cart = JsonConvert.DeserializeObject<CartViewModel>(HttpContext.Session.GetString("CartSession"));
            bool myBool = await _itemLogic.CreateOrderAsync(cart);

            if (myBool)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErrorText = "Hey guy, there was an error!";
                return View("Error");
            }
            //_itemLogic.CreateCustomer(model);
            return View("Verify"/*, model*/);
        }




    }
}

Project_P1/MvcLayer/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer;
using ModelsLibrary;

namespace MvcLayer.Controllers
{
    public class OrderController : Controller
    {
        private readonly ILogger<OrderController> _logger;

        private readonly IOrderLogic _orderLogic;
        //create a constructor into which i'll inject the business layer.
        public OrderController(IOrderLogic orderLogic, ILogger<OrderController> logger)
        {
            this._orderLogic = orderLogic;
            this._logger = logger;
        }
        // GET: OrderController
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetOrders()
        {
            //ViewData.Add("CustomerId", id);
            return RedirectToAction("Orders");
        }
        public async Task<ActionResult> Orders(int id)
        {
            List<Order> orders = await _orderLogic.OrderListAsync(id);
            //ViewData.Add("CustomerId", id);
            if(orders.Count()==0)
            {
                return RedirectToAction("Locations", "Shop");
            }
            return View(orders);
        }
        public async Task<ActionResult> StoreHistory(int id)
        {
            List<Order> orders = await _orderLogic.StoreOrderListAsync(id);
            //ViewData.Add("CustomerId", id);
            return View(orders);
        }
        // GET: OrderController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            List<OrderItem> orderItems = await _orderLogic.OrderItemListAsync(id);
            return View(orderItems);
        }

        
    }
}

Project_P1/MvcLayer/Controllers/ShopController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ModelsLibrary;
using BusinessLayer;
using Microsoft.Extensions.Logging;
using ModelsLibrary.ViewModels;
using Newtonsoft.Json;

namespace MvcLayer.Controllers
{
    public class ShopController : Controller
    {
        private readonly ILogger<ShopController> _logger;

        private readonly IAccountLogic _accountLogic;
        //create a constructor into which i'll inject the business layer.
        public ShopController(IAccountLogic accountLogic, ILogger<ShopController> logger)
        {
            this._accountLogic = accountLogic;
            this._logger = logger;
        }
        // GET: ShopController
        public ActionResult Index()
        {
            return View();
        }

        // GET: ShopController/Details/5
        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: ShopController/Create
        public ActionResult Create()
        {
            return View();
        }
        
        public async Task<ActionResult> Locations(int id)
        {
            List<Store> locations = await _accountLogic.LocationListAsync();
            ViewData.Add("CustomerId", id);
            return View(locations);
        }
    }
}

Project_P1/MvcLayer/Views/Shop/Details.cshtml
@model ModelsLibrary.Store

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Store</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StoreStreet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StoreStreet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StoreCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StoreCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StoreState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StoreState)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StoreZip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StoreZip)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.StoreId">Edit</a> |*@
    <a asp-action="Index">Back to List</a>
</div>

Project_P1/MvcLayer/Views/Shop/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

Project_P1/MvcLayer/Views/Shop/Locations.cshtml
@model IEnumerable<ModelsLibrary.Store>

@{
    ViewData["Title"] = "Locations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Choose the location nearest to you</h1>

<p>
    <a asp-controller="Order" asp-action="Orders" asp-route-id="@ViewData["CustomerId"]">Your Order History </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StoreStreet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoreCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoreState)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoreZip)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StoreStreet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StoreCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StoreState)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StoreZip)
            </td>
            <td>
                @{
                    var parms = new Dictionary<string, string>
                    {
                    { "CustomerId", ViewData["CustomerId"].ToString() },
                    {"StoreId", item.StoreId.ToString() }
                    };
                }
                <a asp-controller="Item" asp-action="CreateCart" asp-all-route-data="parms">Choose Store</a> |
                <a asp-controller="Order" asp-action="StoreHistory" asp-route-id="@item.StoreId">Order History</a>
            </td>
        </tr>
}
    </tbody>
</table>

Project_P1/MvcLayer/Views/Shop/ToItem.cshtml
@{
    ViewData["Title"] = "ToItem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ToItem</h1>